// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqAHg9v3azXLfX4EKSO7lott43kXnApf8',
    appId: '1:204197319739:web:dcb91dd673e8736239381e',
    messagingSenderId: '204197319739',
    projectId: 'learnsearch-7b659',
    authDomain: 'learnsearch-7b659.firebaseapp.com',
    storageBucket: 'learnsearch-7b659.firebasestorage.app',
    measurementId: 'G-9GL9SFVLR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt2c6BgesbZSkx-NxDbwREdhqHLvXpa6w',
    appId: '1:204197319739:android:1cf0eefa4c1e7dfa39381e',
    messagingSenderId: '204197319739',
    projectId: 'learnsearch-7b659',
    storageBucket: 'learnsearch-7b659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOq6hhasAZ6xyf3UtuUckkJaKvG5QLIHI',
    appId: '1:204197319739:ios:32f50bc7426f1e8539381e',
    messagingSenderId: '204197319739',
    projectId: 'learnsearch-7b659',
    storageBucket: 'learnsearch-7b659.firebasestorage.app',
    iosBundleId: 'com.example.searchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOq6hhasAZ6xyf3UtuUckkJaKvG5QLIHI',
    appId: '1:204197319739:ios:32f50bc7426f1e8539381e',
    messagingSenderId: '204197319739',
    projectId: 'learnsearch-7b659',
    storageBucket: 'learnsearch-7b659.firebasestorage.app',
    iosBundleId: 'com.example.searchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqAHg9v3azXLfX4EKSO7lott43kXnApf8',
    appId: '1:204197319739:web:cb756a8a9fb577c939381e',
    messagingSenderId: '204197319739',
    projectId: 'learnsearch-7b659',
    authDomain: 'learnsearch-7b659.firebaseapp.com',
    storageBucket: 'learnsearch-7b659.firebasestorage.app',
    measurementId: 'G-YM2EVLZTXZ',
  );
}
